//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scoffolding.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        public System.Guid ProductId { get; set; }

        [Display(Name = "Product Name:")]
        public string Name { get; set; }
        [Display(Name = "Product Price:")]
        public Nullable<decimal> Price { get; set; }
    }
}
