//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMovieApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Single
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Actress1 { get; set; }
        public string Actress2 { get; set; }
        public string Actress3 { get; set; }
        public string Actress4 { get; set; }
        public string Actress5 { get; set; }
        public string Actress6 { get; set; }
        public string Actress7 { get; set; }
        public string Actress8 { get; set; }
        public string Actress9 { get; set; }
        public string Studio { get; set; }
        public Nullable<double> Case { get; set; }
        public Nullable<double> Position { get; set; }
        public string F15 { get; set; }
    }
}
